### ISSUE TITLE
Plugin not marked with @threadSafe

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-maven-plugin#1]
It would be good to have the plugin allow parallel execution, this speeds up maven builds on new machines.
Right now when I do a mvn -T1 on a dual core cpu I get:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in rultor-users:
[WARNING] org.codehaus.mojo:xml-maven-plugin:1.0
[WARNING] com.ning.maven.plugins:maven-duplicate-finder-plugin:1.0.4
[WARNING] com.jcabi:jcabi-maven-plugin:0.7.22
[WARNING] *****************************************************************
```

**Comment by dmarkov** [comment]
@cyberone the task is your hands for the last 12 days.. keep in mind that if it's not closed in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -30 added to your rating, current score is: [-100](http://www.netbout.com/b/35076?open=rating)

**Comment by cyberone** [comment]
@dmarkov please review https://github.com/jcabi/jcabi-maven-plugin/pull/27

**Comment by dmarkov** [comment]
@cyberone you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, current score is: [-550](http://www.netbout.com/b/35076?open=rating)

**Comment by dmarkov** [comment]
@dpisarenko the task is yours, go ahead

**Comment by dpisarenko** [comment]
@krzyk How can I reproduce this error?

When I run `mvn -T 1C clean install -Pqulice` on my dual-core machine (inside jcabi-maven-plugin directory), I don't see the error.

**Comment by dpisarenko** [comment]
@krzyk  When I run the same command in the rultor directory (as you probably did), I see the following message, but no warning.

```
[INFO] Scanning for projects...
[INFO]
[INFO] Using the MultiThreadedBuilder implementation with a thread count of 2
```

**Comment by dpisarenko** [comment]
@yegor256 `rultor-users` (where the error occured) seems to be an old project. Does it make sense to check out rultor-0.2 ( https://github.com/rultor/rultor/tree/rultor-0.2 ) and try to reproduce the error there?

**Comment by krzyk** [comment]
@dpisarenko this information shows on maven 3.1.x, they removed explicit warning in 3.2.x, but `@threadSafe` annotation doesn't appear to be deprecated so I would still add it to the plugin

**Comment by dpisarenko** [comment]
@dmarkov Please review my PR https://github.com/jcabi/jcabi-maven-plugin/pull/28 .

**Comment by dpisarenko** [comment]
@krzyk The bugfix has been merged. Please look at it, and if everything is OK, close the issue. Thanks!

**Comment by krzyk** [comment]
thanks

**Comment by dmarkov** [comment]
@dpisarenko Much appreciated! **31 mins** was added to your account, payment ID `50573195`; +31 added to your rating, current score is: [+401](http://www.netbout.com/b/35089?open=rating)

**Comment by dmarkov** [comment]
the last puzzle `1-6356edfc`/#21 originated from here solved
