### ISSUE TITLE
Missing documentation about JSR-303

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-maven-plugin#13]
Currently when one wants to use jcabi maven plugin in their project they will see such text in build log:
```
[ERROR] JSR-303 validator failed to initialize: Unable to instantiate Configuration. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)
```

The link provided doesn't explain what to do in case of plugin. I think that there should be info on the project page how to really fix the problem.

To get rid of this warning one has to add validator as a dependency not to the project but to the plugin:
```
                <plugin>
                    <groupId>com.jcabi</groupId>
                    <artifactId>jcabi-maven-plugin</artifactId>
                    <dependencies>
                        <dependency>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-validator</artifactId>
                            <version>5.0.0.Final</version>
                            <scope>runtime</scope>
                        </dependency>
                    </dependencies>
                </plugin>

```

**Comment by dmarkov** [comment]
@flexelem you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, current score is: -125

**Comment by dmarkov** [comment]
@nhekfqn this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by nhekfqn** [comment]
@dmarkov pull request sent https://github.com/jcabi/jcabi-maven-plugin/pull/29

**Comment by nhekfqn** [comment]
@dmarkov related pull request has been merged.

**Comment by yegor256** [comment]
@nhekfqn ask the reporter to close it

**Comment by nhekfqn** [comment]
@krzyk Could you please close the ticket?

**Comment by krzyk** [comment]
thanks

**Comment by nhekfqn** [comment]
@dmarkov the ticket has been closed.

**Comment by nhekfqn** [comment]
@dmarkov Can we please deploy and give me a payment please?

**Comment by dmarkov** [comment]
@nhekfqn I just added **30 mins** to your account, many thanks for your contribution..

added +30 to your rating, now it is equal to [+105](http://www.netbout.com/b/35123?open=rating)
