### ISSUE TITLE
AjcMojoTest.java:72-73: The test is disabled because...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-maven-plugin#21]
Puzzle `1-6356edfc` in `src/test/java/com/jcabi/maven/plugin/AjcMojoTest.java:72-73` has to be resolved: The test is disabled because I can't make it working. Let's try to enable it and fix.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by darkled** [comment]
@dmarkov puzzle should be resolved and changes were merged, please, check it.

**Comment by dmarkov** [comment]
@darkled you're working with this ticket for the last 12 days. If it's not closed within the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget to remove the TODO puzzle from the source code. -30 to your rating, your total score is [-60](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@dmarkov @yegor256 I am not sure these -30 are correct, aren't they?

**Comment by darkled** [comment]
@dmarkov would you mind to close the issue, please, if it is ok now?

**Comment by darkled** [comment]
@yegor256 this issues stays without any response from creator for 9 days. Could you help with it, please?

**Comment by yegor256** [comment]
@darkled which pull request fixed the problem?

**Comment by darkled** [comment]
@yegor256 PR #23

**Comment by yegor256** [comment]
@dmarkov will be closed today or tomorrow the latest. if this doesn't happen, message me again

**Comment by darkled** [comment]
@yegor256 thank you

**Comment by darkled** [comment]
@yegor256 still nothing happened with this issue...

**Comment by dmarkov** [comment]
Thanks, closed

**Comment by dmarkov** [comment]
@darkled **30 mins** sent to your balance (ID `50344882`), many thanks!... +30 added to your rating, at the moment it is: [+195](http://www.netbout.com/b/35091?open=rating)
