### ISSUE TITLE
Error: No appenders could be found for logger (org.jboss.logging)

### ISSUE THREAD

**Issue by asinyagin** [jcabi/jcabi-maven-plugin#22]
I got this message when I built a project using jcabi-maven-plugin. There is the same warning in jcabi-github build: http://www.rultor.com/t/782-55782809.

I turned on log4j debug messages and got:
```
log4j: Trying to find [log4j.xml] using context classloader ClassRealm[plugin>com.jcabi:jcabi-maven-plugin:0.9.3, parent: sun.misc.Launcher$AppClassLoader@744957c7].
log4j: Trying to find [log4j.xml] using ClassRealm[plugin>com.jcabi:jcabi-maven-plugin:0.9.3, parent: sun.misc.Launcher$AppClassLoader@744957c7] class loader.
log4j: Trying to find [log4j.xml] using ClassLoader.getSystemResource().
log4j: Trying to find [log4j.properties] using context classloader ClassRealm[plugin>com.jcabi:jcabi-maven-plugin:0.9.3, parent: sun.misc.Launcher$AppClassLoader@744957c7].
log4j: Trying to find [log4j.properties] using ClassRealm[plugin>com.jcabi:jcabi-maven-plugin:0.9.3, parent: sun.misc.Launcher$AppClassLoader@744957c7] class loader.
log4j: Trying to find [log4j.properties] using ClassLoader.getSystemResource().
log4j: Could not find resource: [null].
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Looks like jcabi-maven-plugin should have its own log4j.properties like maven-javadoc-plugin for example (https://github.com/apache/maven-plugins/blob/trunk/maven-javadoc-plugin/src/main/resources/log4j.properties).

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@maurezen please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@asinyagin thanks for reporting! I topped your account for 15 mins, transaction 49952107

**Comment by maurezen** [comment]
Created a pull request here #24

@dmarkov shouldn't this task also be labeled after me?

**Comment by maurezen** [comment]
@asinyagin the pull request #24 is merged, please close the issue.

**Comment by dmarkov** [comment]
@maurezen **30 mins** was added to your account, many thanks for your contribution!

+30 added to your rating, current score is: [+360](http://www.netbout.com/b/35102?open=rating)
