### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-maven-plugin#25]
Copyright part in license sections still features 2014.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@palyuga it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@maurezen thanks a lot for reporting, **15 mins** added to your acc, pmt ID `49975504`

**Comment by palyuga** [comment]
@maurezen merged to master now, close this issue, please

**Comment by dmarkov** [comment]
@palyuga paid, thanks, added **30 mins** to your account, payment `50255789`

added +30 to your rating, now it is equal to +105
