### ISSUE TITLE
@Aspect and @Autowired

### ISSUE THREAD

**Issue by hellobigbean** [jcabi/jcabi-maven-plugin#33]
I use `@Aspect` in our class(and no jcabi annotation be used ) and use `@Autowired` in some field , but I found out the class be compiled by "jcabi-maven-plugin" ,such as 

```
  public static boolean hasAspect()
  {
    return ajc$perSingletonInstance != null;
  }
```

And the problem is  field not be autowired into my class .

How  "jcabi-maven-plugin"  deal with `@Aspect` ?

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@hellobigbean I'm not sure I understand the problem. Can you explain what you're trying to do and what doesn't work?

**Comment by hellobigbean** [comment]
@yegor256 , Pls ref to https://github.com/jcabi/jcabi-maven-plugin/issues/36  issued by  colleague @tingt 。
