### ISSUE TITLE
The jcabi-maven-plugin initialized the class(with @Aspectj annotation) twice. How jcabi-maven-plugin deal with @Aspectj  and spring-aop ?

### ISSUE THREAD

**Issue by tingt** [jcabi/jcabi-maven-plugin#36]
**The jcabi-maven-plugin initialized the class(with @Aspectj annotation) twice. How jcabi-maven-plugin deal with @Aspectj  and spring-aop ?**
Here is my code.
AopUtils.java
```java
@Component
@Configurable
@Aspect
public class AOPUtils {
	@Autowired 
	public ApplicationContext appContext;
	public AOPUtils(){
		System.out.println("aop utils " + this);
	}
	@Around("execution(public * aop.Logic.handleCommand(..))")
    public Object timesAround(ProceedingJoinPoint point) throws Throwable{
		 System.out.println("========================enter AOPUtils class");
    	 Object result = null ;
    	 StopWatch sw = new StopWatch(this.toString());
         try {
             sw.start(point.getSignature().getName());
             result = point.proceed();
             System.out.println("=========================appContext : " + appContext); 
         } finally {
             sw.stop();
         }
		return result;
	}
}
```
Logic.java
```java
@Service
public class Logic {
	public String  handleCommand() {
		return "handleCommand";
	}
}
```
default-spring.xml
```xml
<aop:aspectj-autoproxy proxy-target-class="true" />
```
Tester.java
```java
public static void main(String[] args) {
		ApplicationContext ctx = new ClassPathXmlApplicationContext("default_spring.xml");
		
		Logic logic = ctx.getBean(Logic.class);
		String result = logic.handleCommand();
		System.out.println("======================"+result);
	}
}
```
**if use the maven-compiler-plugin compile the classes, run the Tester, result is :**
*aop utils aop.AOPUtils@3b1d04*
*=========================enter AOPUtils*
*=========================appContext : org.springframework.context.support.ClassPathXmlApplicationContext@a01335: startup date [Mon Jun 29 16:55:27 CST 2015]; root of context hierarchy*
*======================handleCommand*

**but if use the jcabi-maven-plugin compile the classes, run the Tester, result is :**
*aop utils aop.AOPUtils@cb6009*
*aop utils aop.AOPUtils@e28b9*
*========================enter AOPUtils*
*=========================appContext : null*
*======================handleCommand*

**AopUtils is initialized twice ,and ApplicationContext return null.**
When check the class file, I found jcabi add something in the AopUtils.class.
```java
public class AOPUtils { 
//add by jcabi
	static { 
		try { 
			ajc$postClinit(); 
			} catch (Throwable localThrowable) { 
				ajc$initFailureCause = localThrowable; 
				} 
		} 
	public static AOPUtils aspectOf() { 
		if (ajc$perSingletonInstance == null) 
			throw new org.aspectj.lang.NoAspectBoundException("aop.AOPUtils", ajc$initFailureCause); 
	    return ajc$perSingletonInstance; 
	    } 
	public static boolean hasAspect() { 
		return ajc$perSingletonInstance != null; 
		}
     }
 //add by jcabi end
  
  @org.springframework.beans.factory.annotation.Autowired
  public org.springframework.context.ApplicationContext appContext;
  
  public AOPUtils()
  {
    System.out.println("aop utils " + this);
  }
....
```
**How jcabi deal with the @Aspectj and spring-aop ?**

**Thanks!**

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@tingt I'm not sure how to answer this... I think that spring-aop has its own weaving mechanism. You don't need to use jcabi-maven-plugin at all. Spring will do all this work for you.

**Comment by tingt** [comment]
@yegor256  all right, thank you very much.
