### ISSUE TITLE
jcabi-ajc.log

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-maven-plugin#37]
Looks like recent version of aspectj generates `jcabi-ajc.log` file in `/target/classes` directory when `ajc` goal is running. We should delete it or prevent it from being created. Or, even better, move it to `/target`. It shouldn't stay in `/target/classes`

**Comment by dmarkov** [comment]
@yegor256 this task will get someone's attention soon

**Comment by dmarkov** [comment]
@krzyk it's yours, please help, budget is 30 mins

**Comment by dmarkov** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-12637add

**Comment by krzyk** [comment]
@yegor256 here's PR #38

**Comment by krzyk** [comment]
@yegor256 please close this issue,  code changes have been merged

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`

**Comment by krzyk** [comment]
@yegor256 please close this issue, thanks

**Comment by krzyk** [comment]
@dmarkov please give me more time here

**Comment by dmarkov** [comment]
> @dmarkov please give me more time here

@krzyk sure, thanks for telling me, take your time

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by dmarkov** [comment]
@krzyk paid, thanks, added **30 mins** to your account, payment `61629226`, 262 hours and 55 mins was spent... +30 added to your rating, current score is: [+4438](http://www.netbout.com/b/35035?open=rating)
