### ISSUE TITLE
AJC Classpath issue with Maven multi-modules project

### ISSUE THREAD

**Issue by mgreau** [jcabi/jcabi-maven-plugin#41]
## Problem

In a multi-module Maven project, when your Aspect class and the Annotation class are in different Maven modules, AJC can't weave classes if the artifacts of the project (JARs) are not available in a Maven repository.

AJC generates the following error because it can't find the related Annotation in the Classpath.

```
Thu Jan 14 14:38:07 UTC 2016
[warning] build config error: skipping missing, empty or corrupt aspectpath entry: /root/.m2/repository/com/mgreau/jcabi/ajc/commons/1.0-SNAPSHOT/commons-1.0-SNAPSHOT.jar

[warning] incorrect classpath: /root/.m2/repository/com/mgreau/jcabi/ajc/commons/1.0-SNAPSHOT/commons-1.0-SNAPSHOT.jar

com/mgreau/jcabi/ajc/aspects/MethodReturn42.java [error] Type referred to is not an annotation type: com$mgreau$jcabi$ajc$commons$Return42```
```

## Cause

It's due to the fact that the Classpath generated by the **jcabi-maven-plugin** for the **ajc** command is only generated with paths to local Maven artifacts (JARs in the .m2 repository).
And as the Annotation is in another Maven module, the classpath should instead reference this module path (target/classes) instead of a link to the JAR in the .m2 repository that doesn't exist.

## Example

I've created a sample project at **https://github.com/mgreau/jcabi-ajc-classpath-issue** to reproduce the error.
The Maven project layout is as below:

```
- jcabi-ajc-classpath-issue
  |- commons
      |- scr/main/java/
          |+ com.mgreau.jcabi.ajc.commons.Return42.java (@interface)
  |- aspects
      |- scr/main/java/
          |+ com.mgreau.jcabi.ajc.Sum.java
          |+ com.mgreau.jcabi.ajc.aspects.MethodReturn42.java (@Aspect)
      |- scr/test/java/
          |+ com.mgreau.jcabi.ajc.SumTest.java

```

The ```MethodReturn42``` class should weave all methods annotated with @Return42.
The ```SumTest#shouldReturn42``` test shows that the result is 42 (class weaved) or 12 (class not weaved) depending to the fact that the **commons-1.0-SNAPSHOT** JAR is available in the .m2 repository or not.

## See it in action

To reproduce this error, just execute the following commands:
```
git clone https://github.com/mgreau/jcabi-ajc-classpath-issue
cd jcabi-ajc-classpath-issue
docker-compose up
```

You can find the result of this command at https://github.com/mgreau/jcabi-ajc-classpath-issue/blob/master/README.adoc#docker-way

To really see what happen, the best way is to display and compare the test classpath generated by Maven (with -X option) and the classpath used by the ajc command.
You will see that the ajc classpath contains path to a JAR in the .m2 repository that doesn't exist.

## Solution

We have to **find out how Maven handles its compile and test classpath** for multi-modules projects because Maven generates the right classpath with paths to JAR files in the .m2 repository or paths to target/classptah of the reactor project.

Then IMO, the solution needs to be apply in this ```classpath``` method:
* https://github.com/jcabi/jcabi-maven-plugin/blob/master/src/main/java/com/jcabi/maven/plugin/AjcMojo.java#L305-L336

WDYT?

**Comment by mgreau** [comment]
I added another Docker configuration in the docker-compose.yml file of the sample project to validate the fix proposed.

So, now with:
```
git clone https://github.com/mgreau/jcabi-ajc-classpath-issue
cd jcabi-ajc-classpath-issue
docker-compose up
```
You should have the following results (from the 3 tests containers):
* test-ko_1          | [INFO] BUILD FAILURE
 * mvn clean test with latest jcabi-maven-plugin release version (0.13.2)
* test-ok_1          | [INFO] BUILD SUCCESS
 * this the container with the workaround (clean install first to have JAR into .m2 local repository)
* test-ok-with-fix_1 | [INFO] BUILD SUCCESS
 * this is the container with the PR 41 for jcabi-maven-plugin

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@mgreau I haven't seen this before, but I totally understand what the problem is. Can you suggest a fix/PR?

**Comment by mgreau** [comment]
Yes, I already did it with this PR :) 

https://github.com/jcabi/jcabi-maven-plugin/pull/42

**Comment by mgreau** [comment]
Hi, any news on this issue?
Can you confirm this PR 
https://github.com/jcabi/jcabi-maven-plugin/pull/42 fixed it? Thanks

**Comment by mgreau** [comment]
The PR #42 has been merged and it fixes this issue, can you confirm?

**Comment by amihaiemil** [comment]
@mgreau To put it simple, the way I understood it is the following: you have your project structure and  when you run ``mvn clean test`` it fails. Then, with the fix from #42 ``mvn clean test`` should pass? 

I tried it like this (without any docker stuff: took down your example project, and ran ``mvn clean test`` with ``jcabi-maven-plugin`` **before** your change, and with ``jcabi-maven-plugin`` **after** your change (luckily it's only 1 commit so it is easy to distinguish). The behaviour was the same. 

Did I understand it right? If yes, would you please also do my steps and confirm the changes do not actually affect the behaviour? 

Thank you & best regards, 
Mihai Andronache

**Comment by amihaiemil** [comment]
@mgreau  I used ``jcabi-maven-plugin`` the following way: I took down 2 versions (the latest and the one before your changes). I built the one I wanted to use (``mvn clean install -DskipTests -Dinvoker.skip=true``) and put its version (1.0-SNAPSHOT) in your projecf's pom.xml.

**Comment by mgreau** [comment]
As you can see here https://github.com/mgreau/jcabi-ajc-classpath-issue/tree/master/docker I use docker and specific shell (maven command) for each case in order to have an empty maven local repository because it fails when the .m2 repo is empty because the SNAPSHOT is not available in the repo (and itis what happens when we do a release).

**Comment by amihaiemil** [comment]
@mgreau I understood that and I alsi madw sure that comons snapshot jar is not in the m2 local repo. And, like I said, mvn clean install acted the same with and without your changes. Again, the commons snapshot jar was never in the local repo.

**Comment by amihaiemil** [comment]
@mgreau the way I understand it, the changes did not fix the problem. Please let me know if I'm right. If I am, then I will revert the commit so that ticket #48 can be closed and then this ticket can continue.

**Comment by amihaiemil** [comment]
@mgreau I found the problem, it is not what I initially thought. So your changes did fix the issue in this ticket. Please close it. Thanks. 

Br,
Mihai Andronache

**Comment by mgreau** [comment]
Ok, thanks
