### ISSUE TITLE
Add option to put unwoven classes in a directory

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-maven-plugin#45]
When doing weaving one can leacve unwoven classes in the original directory and create woven classes in given directory (using `classesDirectory`), with optional replacement of the originals with the woven ones.

But it would be beneficial to have the other way around, store the unwoven classes in some predefined directory (e.g. `unwovenClassesDirectory`, or just hardcoded to e.g. `unwoven`).

This is to support extended FindBugs detectors that sometimes give false positives when run on AspectJ woven classes.

Currently there is no easy way to have woven classes packaged in jar and run FindBugs on the unwoven classes.

<hr id='w'>

**Comment by dmarkov** [comment]
@krzyk this task will get someone's attention soon

**Comment by dmarkov** [comment]
@krzyk thanks for the ticket, your account was topped for 15 mins, payment 78357403

**Comment by krzyk** [comment]
@yegor256 Could you dispatch this issue? It will reduce the amount of work in teamed/qulice#706 (or rathere future rework).

**Comment by yegor256** [comment]
@dmarkov pls assign @amihaiemil to this

**Comment by dmarkov** [comment]
> @dmarkov pls assign @amihaiemil to this

@yegor256 OK @amihaiemil please start, the task is yours

**Comment by amihaiemil** [comment]
@dmarkov I created PR #46 for this issue. Please assign a reviewer. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #46 for this issue. Please assign a reviewer. Thanks. 

@amihaiemil will do soon

**Comment by amihaiemil** [comment]
@krzyk Can this issue be closed now, or do you think there's something else I should do?

**Comment by krzyk** [comment]
@amihaiemil do I see it correctly that by default there is no `unwoven` directory?

**Comment by krzyk** [comment]
@amihaiemil actually I think that your current solution doesn't do ajc into `classes` directory, as its content doesn't have the aspects that I've added (usually there are more `.class` files there), and the content of `uvowen` directory is identical to the `classes` directory

**Comment by amihaiemil** [comment]
@krzyk To your first comment: Yes, by default there is no ``unwoven`` directory... It has to be specified and be different than ``classesDirectory`` and ``${project.build.outputDirectory}`` - this is because almost always the ``classesDirectory`` and ``${project.build.outputDirectory}`` will coincide... In the case when the 2 do not coincide, you don't want your project's compiled classes to be replaced with whatever classes you've woven, and also I think you don't want them mixed up either.

**Comment by amihaiemil** [comment]
@krzyk To your second comment: My solution does not interfeer with the woving logic. The copy is done before everything else. If ``unwovenClassesDir`` is specified and ok. If the ``ajc`` does not seem to execute correctly, I think it's something wrong in the method ``executeAJC()`` ? But I never toched that. Can you give the steps to reproduce the problem? Thanks.

**Comment by krzyk** [comment]
@amihaiemil 
1. Why it has to be specified if this will be the default case? Every jcabi project uses jcab-maven-plugin, and every one uses qulice. Without `unwoven` directory qulice will be failing.

2. Yes it interferes, now no class is woven, if I don't configure the jcabi-maven-plugin and use the default from jcabi-parent:
```
                      <executions>
                            <execution>
                                <id>jcabi-ajc-compile</id>
                                <phase>process-classes</phase>
                                <goals>
                                    <goal>ajc</goal>
                                </goals>
                                <configuration>
                                    <tempDirectory>${project.build.directory}/jcabi-ajc</tempDirectory>
                                    <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                                    <aspectsDirectories>
                                        <directory>${project.basedir}/src/main/aspect</directory>
                                    </aspectsDirectories>
                                </configuration>
                            </execution>
```
There are no *woven* classes in `classes` directory, which breaks what we had earlier.

**Comment by krzyk** [comment]
@amihaiemil I think the problem is that by default you made `outputDirectory` same as `unwovenClassesDir`, so probably the other overwrites the first or something.
Basically, before your changes it was working, after your changes it stopped.

**Comment by amihaiemil** [comment]
@krzyk I didn't implement it thinking of qulice and our particular need... I implemented it so it would be ok for whoever uses the plugin... Why should it be a blackbox? Other users will wonder why is the "unwoven" directory created and why are the classes copied there if nothing was specified.

Do you think the default should be the ``unwoven`` directory, if nothing is specified?

In your above configuration you can specify 
``<unwovenClassesDir>unwoven<unwovenClassesDir>`` and it should work. Also, it makes no sense to specify ``<classesDirectory>${project.build.outputDirectory}<classesDirectory>`` - that is its default value anyway.

**Comment by krzyk** [comment]
@amihaiemil It shouldn't be a black box, but the default settings should be useful for us, you just need to add an option to disable it, not to enable.

And users might already wonder why we have `jcabi-ajc` or `jcabi-ajc.log`, which are already produced by this plugin.

**Comment by amihaiemil** [comment]
@krzyk Ok, I will make it like this then. Before waving classes will be copied to ``unwoven`` directory, and I will add an option to disable this behaviour. I will do this as soon as I get the change, later today.

**Comment by amihaiemil** [comment]
@krzyk However I still don't really understand what doesn't work anymore? Classes are not woven in ``classesDirectory``? That's strange, you can even look at the code to see what I did - it's pretty simple.   Anyway, I'll look into that case too.

**Comment by dmarkov** [comment]
@krzyk once `45-e72ce9fe`/#47 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by amihaiemil** [comment]
@krzyk I will make this evening a PR with the requested change, but please give the exact reproducing steps (project, <plugin> config in pom.xml etc) of the problem you mentioned about weaving classes.
 
I tested and it seems to work just fine. I made a project with some classes and aspects from jcabi-aspects and added the following configuration, with the new released plugin: 

https://gist.github.com/amihaiemil/39892a32193a22c95143

Works just fine. 
You said something about default configuration in the parent, but I didn't quite understand.

**Comment by krzyk** [comment]
@amihaiemil 
See attached project
[findbugs-annotations.zip](https://github.com/jcabi/jcabi-maven-plugin/files/163833/findbugs-annotations.zip)


Command
```
mvn clean install assembly:single
java -cp target/findbugs-annotations-1.0-SNAPSHOT-jar-with-dependencies.jar com.qulice.foo.Main s 3
```

Expectred  output:
```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[s, 3]
20:41:39.667 [main] ERROR com.qulice.foo.Main - #main(['s', '3']): in 908.15µs
```


Current output:
```
[s, 3]
```

**Comment by amihaiemil** [comment]
@krzyk The only difference I see in the build, between ``0.13.2`` and ``0.14`` is that for ``0.14``, jcabi-aspects ``@Cachable`` thread finds an error. 

0.13.2:
![image](https://cloud.githubusercontent.com/assets/6305156/13618140/18ebbaca-e58b-11e5-93c7-b71588590c15.png)

0.14: 
![image](https://cloud.githubusercontent.com/assets/6305156/13618181/671977e6-e58b-11e5-8614-e2971d0facf5.png)

I think that error prevents the Loggable aspect from executing, but could not find any logs to see which error it is. I looked in the ``jcabi-aspects`` project, but found nothing usefull.

Do you know anything about this, maybe?

**Comment by amihaiemil** [comment]
@krzyk I opened issue https://github.com/jcabi/jcabi-aspects/issues/216 for the matter above. I am currently waiting for an answer...

**Comment by krzyk** [comment]
@amihaiemil I don't have this error so it is not related:
```
[INFO] --- jcabi-maven-plugin:0.14:ajc (jcabi-ajc-compile) @ findbugs-annotations ---
[INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[INFO] Unwoven classes will be copied to /home/sg0891848/findbugs-annotations/target/unwoven
[INFO] Created temp dir /home/sg0891848/findbugs-annotations/target/jcabi-ajc   
[INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-cacheable for automated cleaning of expired @Cacheable values
[INFO] ajc result: 1 file(s) processed, 0 pointcut(s) woven, 0 error(s), 0 warning(s)
[INFO]                                                                          

```

**Comment by amihaiemil** [comment]
@krzyk I already made the discussed change with ``unwoven`` dir and disabling option - still the same behaviour. I'll make the PR when I find and fix the bug.

**Comment by krzyk** [comment]
@amihaiemil I reported a bug #48, you were right this bug was not introduced by you but in #41.

**Comment by amihaiemil** [comment]
@krzyk I created PR #49 with the discussed change.

**Comment by amihaiemil** [comment]
@krzyk PR #49 has also been merged and closed. Can you close this issue if it's ok? Thanks.

**Comment by amihaiemil** [comment]
@krzyk Don't forget to respond here or close this if it's ok, please. Thanks.

**Comment by krzyk** [comment]
@amihaiemil it is hard to tell if it is OK, because the project is in broken state.

**Comment by krzyk** [comment]
@amihaiemil I see that you used `@EqualsAndHashcode` in the PR which is not an annotation applied by ajc, but a java compiler addon by lombok. It is a completely different way of changing the code, and the lombok one is not related to the weaving done by ajc.

**Comment by krzyk** [comment]
@amihaiemil but the unwoven class appears, so I trust it should work, thanks

**Comment by amihaiemil** [comment]
@dmarkov This issue was closed.

**Comment by dmarkov** [comment]
@amihaiemil Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-36F27724J6932814A`, the task took 408 hours and 41 mins)

+30 to your rating, your total score is [+105](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@krzyk the last puzzle `45-e72ce9fe`/#47 solved
