### ISSUE TITLE
AjcMojo.java:71-72: The new mojo parameter, unwovenClassesDir,...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-maven-plugin#47]
Puzzle `45-e72ce9fe` in `src/main/java/com/jcabi/maven/plugin/AjcMojo.java:71-72` has to be resolved: The new mojo parameter, unwovenClassesDir, should be documented and exemplified on the plugin's site plugin.jcabi.com.... The puzzle was created by Mihai Andronache on 1-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@nesterov-n this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by nesterov-n** [comment]
@dmarkov Please, see my PR #50. Added example for unwovenClassDir parameter

**Comment by dmarkov** [comment]
> @dmarkov Please, see my PR #50. Added example for unwovenClassDir parameter

@nesterov-n OK

**Comment by dmarkov** [comment]
@yegor256 Finished, thanks, closing..
