### ISSUE TITLE
AJC is not executed correctly

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-maven-plugin#48]
After changes done in #41 (44117383ff8ff8aa19e8833644c5ef902e8ef40d) ajc doesn't weave the project that is using jcabi-maven-plugin.

Attached is an example project that does weaving in 4e3c15e6b5921a21fef47b013e4a39a53c993e91 and stops doing it in 44117383ff8ff8aa19e8833644c5ef902e8ef40d

The expected tail output for command:
```
mvn clean install assembly:single && java -cp target/findbugs-annotations-1.0-SNAPSHOT-jar-with-dependencies.jar com.qulice.foo.Main a b c
```
is:
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.360 s
[INFO] Finished at: 2016-03-09T09:13:15+01:00
[INFO] Final Memory: 55M/532M
[INFO] ------------------------------------------------------------------------
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[a, b, c]
09:13:16.034 [main] ERROR com.qulice.foo.Main - #main(['a', 'b', 'c']): in 806.87µs
```
(without the `09:13:16.034 ` and `in 806.87µs` as it will vary).

But what I get is:
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.827 s
[INFO] Finished at: 2016-03-09T09:15:19+01:00
[INFO] Final Memory: 46M/514M
[INFO] ------------------------------------------------------------------------
[a, b, c]
```

Notice the missing `@Loggable` aspect above, there is no `ERROR com.qulice.foo.Main - #main(['a', 'b', 'c'])`.

This is blocking #46 and teamed/qulice#706.

[findbugs-annotations.zip](https://github.com/jcabi/jcabi-maven-plugin/files/178005/findbugs-annotations.zip)

**Comment by krzyk** [comment]
@yegor256 could you dispatch this issue? It is blocking teamed/qulice#706

**Comment by dmarkov** [comment]
@krzyk I will find a developer for the task soon...

**Comment by dmarkov** [comment]
@krzyk thanks for the report, I topped your acc for 15 mins, payment ID `79994251`

**Comment by dmarkov** [comment]
@nesterov-n please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by nesterov-n** [comment]
@krzyk Where can I find sample project to reproduce issue?

**Comment by krzyk** [comment]
@nesterov-n I've updated the issue with an example project

**Comment by nesterov-n** [comment]
@dmarkov please assign someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else

@nesterov-n 30 points was deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else

@nesterov-n got it, someone else will be assigned soon

**Comment by krzyk** [comment]
@yegor256 any chance to proceed with this one?

**Comment by yegor256** [comment]
@dmarkov pls assign @amihaiemil to this

**Comment by dmarkov** [comment]
> @dmarkov pls assign @amihaiemil to this

@yegor256 OK @amihaiemil please proceed, this task is yours

**Comment by amihaiemil** [comment]
@krzyk I left 2 comments on the #41 and currently waiting for a reply there. There are 2 ways of dealing with this ticket. 

1) If the changes in PR #42 fixed ticket #41 but introduced a bug, then we should dig deeper and fix the bug in this ticket (and ticket #41 should actually be closed by now)

and

2) If the changes in PR #42  **did not** fix ticket #41 then I simply revert those changes, we close this ticket and ticket #41 continues on. As you see from the 2 comments of mine, I suspect it's option nr 2)... if I don't get a reply from the original author in 1 or 2 days, I will revert his changes.

Br,
Mihai Andronache

**Comment by amihaiemil** [comment]
@dmarkov I created PR #51 for this issue. Please find a reviewer. Thanks.
cc: @krzyk

**Comment by dmarkov** [comment]
> @dmarkov I created PR #51 for this issue. Please find a reviewer. Thanks.
> cc: @krzyk 

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov I need more time. Waiting for Yegor's approval on the PR.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Waiting for Yegor's approval on the PR. 

@amihaiemil OK, no problem, take your time

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@amihaiemil I'm here

**Comment by amihaiemil** [comment]
@krzyk the pr has been merged and closed

**Comment by krzyk** [comment]
@amihaiemil When I try on a test project, I see only test classes (ending with `Test`) inside the unwoven directory, but no main classes.
I would expect to find main classes there, and test classes inside unwoven-test.

**Comment by amihaiemil** [comment]
@krzyk Are you sure? what project are you testing with? Last time I checked with the findbugs-annotations project it worked ok

**Comment by krzyk** [comment]
@amihaiemil yes, I'm sure. I'm testing on a project that inherits from jcabi-parent, and I override the version of the jcabi-maven-plugin. There are only junit classes in the unwoven directory.

**Comment by krzyk** [comment]
@amihaiemil findbugs-annotations doesn't have test clases

**Comment by amihaiemil** [comment]
@krzyk Ok, I'll have a look into it as soon as I have time

**Comment by krzyk** [comment]
@yegor256 can we release new version of jcabi-maven-plugin?

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by krzyk** [comment]
@yegor256 sorry, it was too soon, let's wait for the second PR to merge

**Comment by amihaiemil** [comment]
@krzyk pr was closed, you can have a look

**Comment by amihaiemil** [comment]
@krzyk ping

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by krzyk** [comment]
@yegor256 could we release a new version of jcabi-maven-plugin?

**Comment by yegor256** [comment]
@krzyk the latest is 0.14.1 and it has all recent changes

**Comment by amihaiemil** [comment]
@dmarkov this ticket is closed

**Comment by dmarkov** [comment]
@amihaiemil Many thanks! **30 mins** were added to your account in Transaction ID `AP-2M6747456B475322E` (task took 1178 hours and 50 mins)

+30 added to your rating, current score is: [+330](http://www.netbout.com/b/36402?open=rating)
