### ISSUE TITLE
JSR-303 validator failed to initialize

### ISSUE THREAD

**Issue by essobedo** [jcabi/jcabi-maven-plugin#53]
While trying to figure out why I get in my project error of types:

- `JSR-303 validator failed to initialize: Unable to instantiate Configuration`
- `JSR-303 validator failed to initialize: HV000183: Unable to load 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead`

I realized that If I add the following dependency to the plugin `jcabi-maven-plugin` I don't have the errors anymore
```
<dependencies>
    <dependency>
       <groupId>javax.el</groupId>
       <artifactId>javax.el-api</artifactId>
       <version>3.0.1-b04</version>
       <scope>runtime</scope>
    </dependency>
</dependencies>
```
The complete plugin configuration that works on my side is then:
```
 <plugin>
    <groupId>com.jcabi</groupId>
    <artifactId>jcabi-maven-plugin</artifactId>
    <version>0.13.2</version>
    <executions>
        <execution>
            <id>jcabi-versionalize-packages</id>
            <goals>
                <goal>versionalize</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>javax.el</groupId>
            <artifactId>javax.el-api</artifactId>
            <version>3.0.1-b04</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@essobedo should be fine in version 0.14.1 thanks!

**Comment by essobedo** [comment]
@yegor256 many thanks
