### ISSUE TITLE
Possibility of usage of jcabi maven plugin in SBT

### ISSUE THREAD

**Issue by mykhailov-egnaroinc** [jcabi/jcabi-maven-plugin#56]
Hi,
First of all, really appreciate your work on this plugin and aspects library as well.

I have a SBT project A which contains annotation and aspect handling, both works fine in scope of this project. However, this project A is injected as jar to other SBT project B and I have to use the annotation (thus an aspect that handles it) from external jar (project A) in project B. As far as I understand from article http://www.yegor256.com/2014/06/01/aop-aspectj-java-method-logging.html this jcabi-maven-plugin helps to omit configuration details in order to handle binary weaving. But the only limitation is that this plugin works for maven only. Are there any workarounds for using it for other build tools like SBT?

Thanks for your answer in advance.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@mykhailov-egnaroinc I don't have any experience with SBT, but you're welcome to submit a pull request, if you can make it work with this builder

**Comment by mykhailov-egnaroinc** [comment]
@yegor256 I've managed to handle binary weaving of jar via AspectJ only using this SBT plugin https://github.com/sbt/sbt-aspectj without usage of jcabi maven plugin. Thanks for your time.

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-maven-plugin#56` was not in scope
